name: Release

on:
  push:
    # 当你推送一个以 'v' 开头的 tag 时触发，例如：v1.0.0
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  # 这个任务负责创建 GitHub Release 草稿
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  # 这个任务负责编译并上传二进制文件
  upload-assets:
    needs: create-release
    strategy:
      matrix:
        # 在下方列出你想编译的所有平台
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          # - target: aarch64-unknown-linux-gnu
          #   os: ubuntu-latest
          # - target: x86_64-pc-windows-msvc
          #   os: windows-latest
          # - target: x86_64-apple-darwin
          #   os: macos-latest
          # - target: aarch64-apple-darwin
          #   os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          # 必填：你的二进制文件名称，即 cargo build 后生成的可执行文件名
          bin: polymarket_test
          # 必填：当前任务的目标平台
          target: ${{ matrix.target }}
          # 必填：用于上传文件的 GitHub Token
          token: ${{ secrets.GITHUB_TOKEN }}